//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teste_servicos.startpage_service {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="startpage_service.startpageSoap")]
    public interface startpageSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFrontPage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetFrontPage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFrontPage", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetFrontPageAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface startpageSoapChannel : teste_servicos.startpage_service.startpageSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class startpageSoapClient : System.ServiceModel.ClientBase<teste_servicos.startpage_service.startpageSoap>, teste_servicos.startpage_service.startpageSoap {
        
        public startpageSoapClient() {
        }
        
        public startpageSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public startpageSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public startpageSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public startpageSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetFrontPage() {
            return base.Channel.GetFrontPage();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetFrontPageAsync() {
            return base.Channel.GetFrontPageAsync();
        }
    }
}
